/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ajoc_prj_cliente_task.Forms;

import com.mycompany.ajoc_prj_cliente_task.Ajoc_server.Ajoc_serverHandler;
import java.io.IOException;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.mycompany.ajoc_prj_cliente_task.Ajoc_Model.Ajoc_Projeto;
import com.mycompany.ajoc_prj_cliente_task.Ajoc_util.Ajoc_parseJson;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import javax.swing.JOptionPane;

    

/**
 *
 * @author Alexssander
 */

public class Ajoc_CadastroTarefa extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ajoc_CadastroTarefa.class.getName());

    /**
     * Creates new form CadastroTarefa
     */
    private Ajoc_serverHandler ajoc_server;
    private final Gson ajoc_gson = new Gson();
    private List<Ajoc_Projeto> ajoc_projetos;

    public Ajoc_CadastroTarefa(Ajoc_serverHandler ajoc_server) {
        initComponents();
        this.ajoc_server = ajoc_server;
        this.Ajoc_fetchProjetos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        Ajoc_txtSalvar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Ajoc_txtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Ajoc_txtDescricao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Ajoc_txtDataFim = new javax.swing.JTextField();
        Ajoc_txtDataCriacao = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Ajoc_txtPrioridade = new javax.swing.JTextField();
        Ajoc_cmbProjetos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        Ajoc_txtSalvar.setBackground(new java.awt.Color(102, 255, 102));
        Ajoc_txtSalvar.setForeground(new java.awt.Color(0, 0, 0));
        Ajoc_txtSalvar.setText("Salvar");
        Ajoc_txtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ajoc_txtSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Ajoc_txtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(Ajoc_txtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Titulo:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Descrição:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Data de criação:");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Data de conclusão:");

        Ajoc_txtDataFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ajoc_txtDataFimActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Prioridade:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Projeto:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ajoc_txtDataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ajoc_txtDataFim)
                .addGap(13, 13, 13))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ajoc_txtPrioridade)
                    .addComponent(Ajoc_txtDescricao)
                    .addComponent(Ajoc_txtNome))
                .addGap(11, 11, 11))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ajoc_cmbProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Ajoc_txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Ajoc_txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Ajoc_txtPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ajoc_cmbProjetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ajoc_txtDataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(Ajoc_txtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cadastro de Tarefas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ajoc_fetchProjetos() {
        try {
            String jsonResposta = this.ajoc_listarProjetos();

            List<Ajoc_Projeto> lista = ajoc_parseListaProjetos(jsonResposta);

            this.ajoc_projetos = lista;

            Ajoc_cmbProjetos.removeAllItems(); // limpa antes
            for (Ajoc_Projeto p : ajoc_projetos) {
                Ajoc_cmbProjetos.addItem(p.getAjoc_nome());
            }

            System.out.println("Projetos carregados: " + ajoc_projetos.size());

        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,
                    "Erro ao buscar projetos no servidor:\n" + e.getMessage(),
                    "Erro de Conexão",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    public String ajoc_listarProjetos() throws IOException {
        return this.ajoc_server.ajoc_enviarMensagem("listar", "projetos", null);
    }

    public List<Ajoc_Projeto> ajoc_parseListaProjetos(String jsonResposta) {
        List<Ajoc_Projeto> lista = new ArrayList<>();

        try {
            JsonObject obj = ajoc_gson.fromJson(jsonResposta, JsonObject.class);
            if (!obj.get("status").getAsString().equals("ok")) {
                return lista;
            }

            JsonArray array = obj.getAsJsonArray("dados");
            for (JsonElement el : array) {
                Ajoc_Projeto p = Ajoc_parseJson.ajoc_parseProjeto(el.toString());
                if (p != null) {
                    lista.add(p);
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        return lista;
    }

    private void Ajoc_txtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ajoc_txtSalvarActionPerformed
        String ajoc_nome = Ajoc_txtNome.getText().trim();
        String ajoc_descricao = Ajoc_txtDescricao.getText().trim();
        String ajoc_prioridade = Ajoc_txtPrioridade.getText().trim();
        String ajoc_dataCriacao = Ajoc_txtDataCriacao.getText().trim();
        String ajoc_dataFim = Ajoc_txtDataFim.getText().trim();

        // 1️⃣ Verifica se o usuário selecionou algum projeto
        int ajoc_indexProjeto = Ajoc_cmbProjetos.getSelectedIndex();
        if (ajoc_indexProjeto < 0 || ajoc_indexProjeto >= ajoc_projetos.size()) {
            JOptionPane.showMessageDialog(this, "Selecione um projeto válido para associar a tarefa.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2️⃣ Obtém o projeto associado da lista
        Ajoc_Projeto ajoc_projetoSelecionado = ajoc_projetos.get(ajoc_indexProjeto);

        // 3️⃣ Monta o Map com os dados da tarefa
        Map<String, String> ajoc_dadosTarefa = new LinkedHashMap<>();
        String ajoc_id = UUID.randomUUID().toString();
        ajoc_dadosTarefa.put("ajoc_id_tarefa", ajoc_id);
        ajoc_dadosTarefa.put("ajoc_nome", ajoc_nome);
        ajoc_dadosTarefa.put("ajoc_descricao", ajoc_descricao);
        ajoc_dadosTarefa.put("ajoc_prioridade", ajoc_prioridade);
        ajoc_dadosTarefa.put("ajoc_data_inicio", ajoc_dataCriacao);
        ajoc_dadosTarefa.put("ajoc_data_fim", ajoc_dataFim);
        ajoc_dadosTarefa.put("ajoc_id_projeto", ajoc_projetoSelecionado.getAjoc_id().toString());

        try {
            String ajoc_resposta = this.ajoc_server.ajoc_enviarMensagem("adicionar", "tarefas", ajoc_dadosTarefa);
            System.out.println(ajoc_dadosTarefa);
            JOptionPane.showMessageDialog(this, ajoc_resposta);

            // Limpa os campos após salvar
            Ajoc_txtNome.setText("");
            Ajoc_txtDescricao.setText("");
            Ajoc_txtPrioridade.setText("");
            Ajoc_txtDataCriacao.setText("");
            Ajoc_txtDataFim.setText("");
            Ajoc_cmbProjetos.setSelectedIndex(-1);

        } catch (IOException ajoc_e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar tarefa: " + ajoc_e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_Ajoc_txtSalvarActionPerformed

    private void Ajoc_txtDataFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ajoc_txtDataFimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ajoc_txtDataFimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    Ajoc_serverHandler ajoc_server = new Ajoc_serverHandler();
    ajoc_server.ajoc_conectar("127.0.0.1", 2014);
    java.awt.EventQueue.invokeLater(() -> new Ajoc_CadastroTarefa(ajoc_server).setVisible(true));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Ajoc_cmbProjetos;
    private javax.swing.JTextField Ajoc_txtDataCriacao;
    private javax.swing.JTextField Ajoc_txtDataFim;
    private javax.swing.JTextField Ajoc_txtDescricao;
    private javax.swing.JTextField Ajoc_txtNome;
    private javax.swing.JTextField Ajoc_txtPrioridade;
    private javax.swing.JButton Ajoc_txtSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    
}
