/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ajoc_prj_cliente_task.Forms;

import com.mycompany.ajoc_prj_cliente_task.Ajoc_server.Ajoc_serverHandler;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Alexssander
 */
public class Ajoc_menu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ajoc_menu.class.getName());

    /**
     * Creates new form Ajoc_menu
     */
    private Ajoc_serverHandler ajoc_server;
    private List<Ajoc_RelatorioProjetos> ajoc_relatorios_proj;
    private List<Ajoc_RelatorioTarefas> ajoc_relatorios_tar;
    private ScheduledExecutorService ajoc_scheduler;

    public Ajoc_menu(Ajoc_serverHandler ajoc_server) {
        initComponents();
        this.ajoc_server = ajoc_server;
        this.ajoc_relatorios_proj = new ArrayList();
        this.ajoc_relatorios_tar = new ArrayList();
        Ajoc_iniciarAtualizacaoPeriodica();
    }

    private void Ajoc_iniciarAtualizacaoPeriodica() {
        ajoc_scheduler = Executors.newSingleThreadScheduledExecutor();

        Runnable tarefaAtualizacao = () -> {
            SwingUtilities.invokeLater(() -> {
                ajoc_relatorios_proj.forEach(relatorio -> relatorio.Ajoc_atualizar());
                ajoc_relatorios_tar.forEach(relatorio -> relatorio.Ajoc_atualizar());
                System.out.println("[SCHEDULER] Relatórios atualizados.");
            });
        };

        ajoc_scheduler.scheduleAtFixedRate(tarefaAtualizacao, 0, 3, TimeUnit.SECONDS);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ajoc_menubar = new javax.swing.JMenuBar();
        ajoc_menuTarefas = new javax.swing.JMenu();
        ajoc_salvarTarefas = new javax.swing.JMenuItem();
        ajoc_relatorioTarefas = new javax.swing.JMenuItem();
        ajoc_menuProjetos = new javax.swing.JMenu();
        ajoc_salvarProjetos = new javax.swing.JMenuItem();
        ajoc_relatorioProjetos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Bem vindo ao sistema para gerenciar Tarefas e Projetos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        ajoc_menuTarefas.setText("Tarefas");

        ajoc_salvarTarefas.setText("Cadastrar");
        ajoc_salvarTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoc_salvarTarefasActionPerformed(evt);
            }
        });
        ajoc_menuTarefas.add(ajoc_salvarTarefas);

        ajoc_relatorioTarefas.setText("Relatório");
        ajoc_relatorioTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoc_relatorioTarefasActionPerformed(evt);
            }
        });
        ajoc_menuTarefas.add(ajoc_relatorioTarefas);

        ajoc_menubar.add(ajoc_menuTarefas);

        ajoc_menuProjetos.setText("Projetos");

        ajoc_salvarProjetos.setText("Cadastrar");
        ajoc_salvarProjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoc_salvarProjetosActionPerformed(evt);
            }
        });
        ajoc_menuProjetos.add(ajoc_salvarProjetos);

        ajoc_relatorioProjetos.setText("Relatório");
        ajoc_relatorioProjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoc_relatorioProjetosActionPerformed(evt);
            }
        });
        ajoc_menuProjetos.add(ajoc_relatorioProjetos);

        ajoc_menubar.add(ajoc_menuProjetos);

        jMenu2.setText("Sair");
        ajoc_menubar.add(jMenu2);

        setJMenuBar(ajoc_menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajoc_salvarTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoc_salvarTarefasActionPerformed
        Ajoc_CadastroTarefa ajoc_cadastro = new Ajoc_CadastroTarefa(this.ajoc_server);
        ajoc_cadastro.setVisible(true);
    }//GEN-LAST:event_ajoc_salvarTarefasActionPerformed

    private void ajoc_relatorioTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoc_relatorioTarefasActionPerformed
        Ajoc_RelatorioTarefas ajoc_rel = new Ajoc_RelatorioTarefas(this.ajoc_server);
        this.ajoc_relatorios_tar.add(ajoc_rel);
        ajoc_rel.setVisible(true);
    }//GEN-LAST:event_ajoc_relatorioTarefasActionPerformed

    private void ajoc_salvarProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoc_salvarProjetosActionPerformed
        Ajoc_CadastroProjeto ajoc_cadastro = new Ajoc_CadastroProjeto(this.ajoc_server);
        ajoc_cadastro.setVisible(true);
    }//GEN-LAST:event_ajoc_salvarProjetosActionPerformed

    private void ajoc_relatorioProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoc_relatorioProjetosActionPerformed
        Ajoc_RelatorioProjetos ajoc_rel = new Ajoc_RelatorioProjetos(this.ajoc_server);
        this.ajoc_relatorios_proj.add(ajoc_rel);
        ajoc_rel.setVisible(true);
    }//GEN-LAST:event_ajoc_relatorioProjetosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Ajoc_serverHandler ajoc_server = new Ajoc_serverHandler();
        ajoc_server.ajoc_conectar("127.0.0.1", 2014);

        // Abre o menu principal e passa o cliente
        java.awt.EventQueue.invokeLater(() -> new Ajoc_menu(ajoc_server).setVisible(true));
    }

    @Override
    public void dispose() {
        if (ajoc_scheduler != null && !ajoc_scheduler.isShutdown()) {
            ajoc_scheduler.shutdownNow(); // para imediatamente
            System.out.println("[SCHEDULER] Parado com sucesso.");
        }
        super.dispose(); // fecha a janela normalmente
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ajoc_menuProjetos;
    private javax.swing.JMenu ajoc_menuTarefas;
    private javax.swing.JMenuBar ajoc_menubar;
    private javax.swing.JMenuItem ajoc_relatorioProjetos;
    private javax.swing.JMenuItem ajoc_relatorioTarefas;
    private javax.swing.JMenuItem ajoc_salvarProjetos;
    private javax.swing.JMenuItem ajoc_salvarTarefas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
